import { apiRequest } from "./apiClient";

const a = (path, options = {}) => apiRequest(path, { role: "admin", ...options });
const id = (value) => encodeURIComponent(value);
export const adminApi = {
  createTurf: (body) => a("/admin/turfs", { method: "POST", body }),
  turfs: (query) => a("/admin/turfs", { query }),
  updateTurf: (turfId, body) => a(`/admin/turfs/${id(turfId)}`, { method: "PUT", body }),
  deleteTurf: (turfId) => a(`/admin/turfs/${id(turfId)}`, { method: "DELETE" }),
  updateTurfMeta: (turfId, body) => a(`/admin/turfs/${id(turfId)}/meta`, { method: "PATCH", body }),
  approveTurf: (turfId, body = {}) => a(`/admin/turfs/${id(turfId)}/approve`, { method: "POST", body }),
  rejectTurf: (turfId, body) => a(`/admin/turfs/${id(turfId)}/reject`, { method: "POST", body }),
  bookings: (query) => a("/admin/bookings", { query }),
  updateBooking: (bookingId, body) => a(`/admin/bookings/${id(bookingId)}`, { method: "PATCH", body }),
  bookingStats: (query) => a("/admin/booking-stats", { query }),
  businesses: (query) => a("/admin/businesses", { query }),
  reviewBusiness: (businessId, body) => a(`/admin/businesses/${id(businessId)}/approval`, { method: "PATCH", body }),
  businessDocuments: (query) => a("/admin/business-documents", { query }),
  businessDocumentDownload: (documentId) => a(`/admin/business-documents/${id(documentId)}/download`),
  reviewBusinessDocument: (documentId, body) => a(`/admin/business-documents/${id(documentId)}/review`, { method: "PATCH", body }),
  venues: (query) => a("/admin/venues", { query }),
  reviewVenue: (venueId, body) => a(`/admin/venues/${id(venueId)}/approval`, { method: "PATCH", body }),
  sports: (query) => a("/sports/admin", { query }),
  createSport: (body) => a("/sports/admin", { method: "POST", body }),
  updateSport: (sportId, body) => a(`/sports/admin/${id(sportId)}`, { method: "PATCH", body }),
  analytics: (query) => a("/analytics/admin", { query }),
  auditLogs: (query) => a("/admin/audit-logs", { query }),
  financialRules: () => a("/financials/admin/rules"),
  updateFinancialRules: (body) => a("/financials/admin/rules", { method: "PATCH", body }),
  ledger: (query) => a("/financials/admin/ledger", { query }),
  payouts: (query) => a("/financials/admin/payouts", { query }),
  settlements: (query) => a("/financials/admin/settlements", { query }),
  createSettlement: (businessId, body = {}) => a(`/financials/admin/settlements/${id(businessId)}`, { method: "POST", body, idempotent: true }),
  transitionSettlement: (settlementId, body) => a(`/financials/admin/settlements/${id(settlementId)}`, { method: "PATCH", body }),
  refundsRequired: (query) => a("/payments/admin/refunds-required", { query }),
  refund: (paymentId, body = {}) => a(`/payments/admin/${id(paymentId)}/refund`, { method: "POST", body, idempotent: true }),
  supportTickets: (query) => a("/support/admin", { query }),
  supportTicket: (ticketId) => a(`/support/admin/${id(ticketId)}`),
  replyToSupportTicket: (ticketId, body) => a(`/support/admin/${id(ticketId)}/replies`, { method: "POST", body }),
  updateSupportTicket: (ticketId, body) => a(`/support/admin/${id(ticketId)}`, { method: "PATCH", body }),
  reviews: (query) => a("/reviews/admin", { query }),
  moderateReview: (reviewId, body) => a(`/reviews/admin/${id(reviewId)}`, { method: "PATCH", body }),
  subscriptionPlans: (query) => a("/subscriptions/admin/plans", { query }),
  createSubscriptionPlan: (body) => a("/subscriptions/admin/plans", { method: "POST", body }),
  updateSubscriptionPlan: (planId, body) => a(`/subscriptions/admin/plans/${id(planId)}`, { method: "PATCH", body }),
  subscriptions: (query) => a("/subscriptions/admin/subscriptions", { query }),
  membershipPlans: (query) => a("/memberships/admin/plans", { query }),
  createMembershipPlan: (body) => a("/memberships/admin/plans", { method: "POST", body }),
  updateMembershipPlan: (planId, body) => a(`/memberships/admin/plans/${id(planId)}`, { method: "PATCH", body }),
  adjustWallet: (userId, body) => a(`/wallet/admin/users/${id(userId)}/adjust`, { method: "POST", body, idempotent: true }),
};
