import { apiRequest } from "./apiClient";

const b = (path, options = {}) => apiRequest(path, { role: "business", ...options });
const id = (value) => encodeURIComponent(value);
export const businessApi = {
  profile: () => b("/business/profile"),
  saveProfile: (body) => b("/business/profile", { method: "PUT", body }),
  documents: () => b("/business/documents"),
  submitDocument: (formData) => b("/business/documents", { method: "POST", body: formData }),
  documentDownload: (documentId) => b(`/business/documents/${id(documentId)}/download`),
  staff: () => b("/business/staff"),
  addStaff: (body) => b("/business/staff", { method: "POST", body }),
  updateStaff: (staffId, body) => b(`/business/staff/${id(staffId)}`, { method: "PATCH", body }),
  removeStaff: (staffId) => b(`/business/staff/${id(staffId)}`, { method: "DELETE" }),
  locations: () => b("/business/locations"),
  createLocation: (body) => b("/business/locations", { method: "POST", body }),
  updateLocation: (locationId, body) => b(`/business/locations/${id(locationId)}`, { method: "PUT", body }),
  removeLocation: (locationId) => b(`/business/locations/${id(locationId)}`, { method: "DELETE" }),
  venues: () => b("/business/venues"),
  createVenue: (body) => b("/business/venues", { method: "POST", body }),
  updateVenue: (venueId, body) => b(`/business/venues/${id(venueId)}`, { method: "PUT", body }),
  facilities: (venueId) => b(`/business/venues/${id(venueId)}/facilities`),
  createFacility: (venueId, body) => b(`/business/venues/${id(venueId)}/facilities`, { method: "POST", body }),
  updateFacility: (venueId, facilityId, body) => b(`/business/venues/${id(venueId)}/facilities/${id(facilityId)}`, { method: "PUT", body }),
  availabilityRules: (venueId, facilityId) => b(`/business/venues/${id(venueId)}/facilities/${id(facilityId)}/availability-rules`),
  saveAvailabilityRules: (venueId, facilityId, body) => b(`/business/venues/${id(venueId)}/facilities/${id(facilityId)}/availability-rules`, { method: "PUT", body }),
  deleteAvailabilityRule: (venueId, facilityId, ruleId) => b(`/business/venues/${id(venueId)}/facilities/${id(facilityId)}/availability-rules/${id(ruleId)}`, { method: "DELETE" }),
  pricingRules: (venueId, facilityId) => b(`/business/venues/${id(venueId)}/facilities/${id(facilityId)}/pricing-rules`),
  createPricingRule: (venueId, facilityId, body) => b(`/business/venues/${id(venueId)}/facilities/${id(facilityId)}/pricing-rules`, { method: "POST", body }),
  updatePricingRule: (venueId, facilityId, ruleId, body) => b(`/business/venues/${id(venueId)}/facilities/${id(facilityId)}/pricing-rules/${id(ruleId)}`, { method: "PUT", body }),
  deletePricingRule: (venueId, facilityId, ruleId) => b(`/business/venues/${id(venueId)}/facilities/${id(facilityId)}/pricing-rules/${id(ruleId)}`, { method: "DELETE" }),
  turfs: (query) => b("/business/turfs", { query }),
  createTurf: (body) => b("/business/turfs", { method: "POST", body }),
  updateTurf: (turfId, body) => b(`/business/turfs/${id(turfId)}`, { method: "PUT", body }),
  deleteTurf: (turfId) => b(`/business/turfs/${id(turfId)}`, { method: "DELETE" }),
  bookings: (query) => b("/business/bookings", { query }),
  bookingStats: (query) => b("/business/booking-stats", { query }),
  updateBooking: (bookingId, body) => b(`/business/bookings/${id(bookingId)}`, { method: "PATCH", body }),
  respondToReview: (reviewId, body) => b(`/business/reviews/${id(reviewId)}/response`, { method: "PATCH", body }),
  analytics: (query) => b("/analytics/business", { query }),
  financialStatement: (query) => b("/financials/business/statement", { query }),
  settlements: (query) => b("/financials/business/settlements", { query }),
  payouts: (query) => b("/financials/business/payouts", { query }),
  subscriptionCheckout: (body) => b("/subscriptions/checkout", { method: "POST", body, idempotent: true }),
  verifySubscription: (body) => b("/subscriptions/verify", { method: "POST", body, idempotent: true }),
  subscription: () => b("/subscriptions/me"),
  cancelSubscription: (body = {}) => b("/subscriptions/cancel", { method: "POST", body }),
  invoices: (query) => b("/invoices/me", { query }),
  createSupportTicket: (body) => b("/support", { method: "POST", body }),
  supportTickets: (query) => b("/support", { query }),
  supportTicket: (ticketId) => b(`/support/${id(ticketId)}`),
  replyToSupportTicket: (ticketId, body) => b(`/support/${id(ticketId)}/replies`, { method: "POST", body }),
};
