import { apiRequest } from "./apiClient";

const user = (path, options = {}) => apiRequest(path, { role: "user", ...options });
export const platformApi = {
  health: () => user("/health"),
  liveness: () => apiRequest("/health/live", { root: true }),
  readiness: () => apiRequest("/health/ready", { root: true }),
  sports: (query) => user("/sports", { query }),
  turfs: (query) => user("/turfs", { query }),
  nearbyTurfs: (query) => user("/turfs/nearby", { query }),
  featuredTurfs: (query) => user("/turfs/featured", { query }),
  trendingTurfs: (query) => user("/turfs/trending", { query }),
  venues: (query) => user("/venues", { query }),
  venue: (id) => user(`/venues/${encodeURIComponent(id)}`),
  facilityAvailability: (id, query) => user(`/venues/facilities/${encodeURIComponent(id)}/availability`, { query }),
  membershipPlans: (query) => user("/memberships/plans", { query }),
  businessSubscriptionPlans: (query) => user("/subscriptions/plans", { query }),
  publicReviews: (query) => user("/reviews", { query }),
  refreshUserToken: (body) => user("/users/refresh-token", { method: "POST", body }),
  getBooking: (id) => user(`/bookings/${encodeURIComponent(id)}`),
  invoices: (query) => user("/invoices/me", { role: "user", query }),
  myReviews: (query) => user("/reviews/me", { role: "user", query }),
  createReview: (body) => user("/reviews", { method: "POST", body }),
  loyalty: (query) => user("/loyalty/me", { query }),
  wallet: (query) => user("/wallet/me", { query }),
  myMemberships: (query) => user("/memberships/me", { query }),
  purchaseMembership: (body) => user("/memberships/purchase", { method: "POST", body, idempotent: true }),
  notifications: (query) => user("/notifications", { query }),
  markNotificationRead: (id, body = {}) => user(`/notifications/${encodeURIComponent(id)}/read`, { method: "PATCH", body }),
  notificationPreferences: () => user("/notifications/preferences"),
  updateNotificationPreferences: (body) => user("/notifications/preferences", { method: "PATCH", body }),
  createSupportTicket: (body) => user("/support", { method: "POST", body }),
  supportTickets: (query) => user("/support", { query }),
  supportTicket: (id) => user(`/support/${encodeURIComponent(id)}`),
  replyToSupportTicket: (id, body) => user(`/support/${encodeURIComponent(id)}/replies`, { method: "POST", body }),
  logout: (body = {}) => user("/users/logout", { method: "POST", body }),
  deleteAccount: () => user("/users/account", { method: "DELETE" }),
  paymentOrder: (bookingId) => user("/payments/orders", { method: "POST", body: { bookingId }, idempotent: true }),
  verifyPayment: (body) => user("/payments/verify", { method: "POST", body, idempotent: true }),
};
